### ISSUE TITLE
Update to Swift 2.2?

### ISSUE THREAD

**Issue by tciuro** [valfer/NewSplitController#1]
I'd love to see this sample app updated with the latest Swift syntax. When opened with Xcode 7.3, there are too many errors and deprecated invocations.

**Comment by valfer** [comment]
mmh, ok, I want to fix them as soon as possible

**Comment by valfer** [comment]
Ok, just updated to Swift 2.2 (XCode 7.3)

**Comment by tciuro** [comment]
Thanks a lot Valerio! 👍🏻
